version: '3'
services:
  angular-ssr:
    build: .
    image: angular-ssr
    ports:
      - '8080:4000'
  nginx-proxy-ssr:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
